USE [master]
GO

/****** Object:  Database [dbCeltrinoDemo]    Script Date: 10/09/2017 08:13:08 ******/
CREATE DATABASE [dbCeltrinoDemo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dbCeltrinoDemo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\dbCeltrinoDemo.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'dbCeltrinoDemo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\dbCeltrinoDemo_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [dbCeltrinoDemo] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbCeltrinoDemo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [dbCeltrinoDemo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dbCeltrinoDemo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dbCeltrinoDemo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dbCeltrinoDemo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dbCeltrinoDemo] SET ARITHABORT OFF 
GO

ALTER DATABASE [dbCeltrinoDemo] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [dbCeltrinoDemo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dbCeltrinoDemo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dbCeltrinoDemo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dbCeltrinoDemo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dbCeltrinoDemo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dbCeltrinoDemo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dbCeltrinoDemo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dbCeltrinoDemo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dbCeltrinoDemo] SET  DISABLE_BROKER 
GO

ALTER DATABASE [dbCeltrinoDemo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [dbCeltrinoDemo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dbCeltrinoDemo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dbCeltrinoDemo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dbCeltrinoDemo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dbCeltrinoDemo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dbCeltrinoDemo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dbCeltrinoDemo] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [dbCeltrinoDemo] SET  MULTI_USER 
GO

ALTER DATABASE [dbCeltrinoDemo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dbCeltrinoDemo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [dbCeltrinoDemo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [dbCeltrinoDemo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [dbCeltrinoDemo] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [dbCeltrinoDemo] SET QUERY_STORE = OFF
GO

USE [dbCeltrinoDemo]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [dbCeltrinoDemo] SET  READ_WRITE 

use dbCeltrinoDemo;

--[dbo].[tbVehicle]
CREATE TABLE [dbo].[tbVehicle](
	[IdVehicle] [uniqueidentifier] NOT NULL,
	[Name] [nchar](100) NOT NULL,
	[Color] [nchar](100) NULL,
 CONSTRAINT [PK_tbVehicle] PRIMARY KEY CLUSTERED 
(
	[IdVehicle] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

-- [dbo].[tbTrack]
CREATE TABLE [dbo].[tbTrack](
	[TrakId] [uniqueidentifier] NOT NULL,
	[IdVehicle] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_tbTrack] PRIMARY KEY CLUSTERED 
(
	[TrakId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[tbTrack]  WITH CHECK ADD  CONSTRAINT [FK_tbTrack_tbTrack] FOREIGN KEY([TrakId])
REFERENCES [dbo].[tbTrack] ([TrakId])
GO

ALTER TABLE [dbo].[tbTrack] CHECK CONSTRAINT [FK_tbTrack_tbTrack]
GO

ALTER TABLE [dbo].[tbTrack]  WITH CHECK ADD  CONSTRAINT [tbVehicle_idVehicle_FK] FOREIGN KEY([IdVehicle])
REFERENCES [dbo].[tbVehicle] ([IdVehicle])
GO

ALTER TABLE [dbo].[tbTrack] CHECK CONSTRAINT [tbVehicle_idVehicle_FK]






